name: Build Safari Extension
on: [push]
jobs:
  build:
    runs-on: macos-latest  # Required for Safari conversion
    steps:
      - uses: actions/checkout@v4
      - uses: bitwarden/safari-web-extension-converter@v1
        with:
          project-root: "."  # Path to your extension (root folder)
          xcode-project-scheme: "FlexRizz (macOS)"  # Optional
